### ISSUE TITLE
Cannot read properties of undefined (reading 'uniqueId')

### ISSUE THREAD

**Issue by mustapha-wang** [cloydlau/json-editor-vue#94]
### Before you start, please make sure to:

- [X] Read the document
- [X] Have tried the latest version
- [X] Search to see if your issue already exists

### Link to minimal reproduction

no 

### Validation

- [X] ⚠️ I understand that invalid, incomplete or superfluous reproduction can lead to this issue being closed

### Describe the bug and steps to reproduce

vue3，raised error: Cannot read properties of undefined (reading 'uniqueId')
`TypeError: Cannot read properties of undefined (reading 'uniqueId')
    at cj (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:401303)
    at _o (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:26375)
    at new n (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:431691)
    at Array.xy (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:566087)
    at ky (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:570411)
    at _o (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:26746)
    at new n (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:575350)
    at Fy (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:593119)
    at Array.Ly (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:594327)
    at ut (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:17025)
    at rr (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:35278)
    at _o (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:26746)
    at new n (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:41596)
    at Array.Uy (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:595009)
    at ut (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:17025)
    at rr (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:35278)
    at _o (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:26746)
    at new n (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:41596)
    at Array.Dy (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:595559)
    at ut (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:17025)
    at ya (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:58354)
    at _o (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:26746)
    at new n (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:59744)
    at Jy (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:596010)
    at _o (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:26746)
    at new n (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:604802)
    at eval (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:1:30428)
    at eval (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:2084:88)
    at callWithErrorHandling (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:18:18)
    at callWithAsyncErrorHandling (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:26:17)
    at hook.__weh.hook.__weh (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:2069:19)
    at flushPostFlushCbs (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:158:41)
    at flushJobs (eval at evaluateModule (http://localhost:3000/js/foil/yjClient.require.js:164:13), <anonymous>:190:5)
`
after so many trace,I found it from \nodejs\npm-global\node_modules\vanilla-jsoneditor\index.js
It is es6,my client is es5, so babel transform it.
but babel has a bug:
in function cj,also has locale variable "W"，it is undefined before use.
`
var W = _interopRequireWildcard(require("lodash-es"));
..........
function cj(e, n, t) {
    var o, i = Qo("jsoneditor:TreeMode"), s = "undefined" == typeof window;
    i("isSSR:", s);
    var l, c, u, d, f, v = co("simple-modal").open, p = (0,
    W.uniqueId)(), m = (0,
    W.uniqueId)(), h = co("absolute-popup"), j = h.openAbsolutePopup, b = h.closeAbsolutePopup, x = !1, w = yf(), $ = n.readOnly, k = n.externalContent, C = n.externalSelection, S = n.mainMenuBar, M = n.navigationBar, E = n.escapeControlCharacters, q = n.escapeUnicodeCharacters, P = n.parser, I = n.parseMemoizeOne, T = n.validator, A = n.validationParser, F = n.pathParser, U = n.indentation, D = n.onError, J = n.onChange, V = n.onChangeMode, H = n.onSelect, W = n.onRenderValue, Q = n.onRenderMenu, Y = n.onRenderContextMenu, K = n.onClassName, Z = n.onFocus, te = n.onBlur, oe = n.onSortModal, re = n.onTransformModal, ie = n.onJSONEditorModal, ae = !1;
`

### Package Manager

npm

**Comment by cloydlau** [comment]
<img width="754" alt="image" src="https://github.com/user-attachments/assets/3c65c823-3815-4eea-aaa2-d5463a10d697">

**Comment by cloydlau** [comment]
There is nothing I can do if you do not provide a reproduction.
